# Generated by Django 2.1.1 on 2019-08-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestSummary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsummary',
            old_name='base_cpu_performance',
            new_name='code_cppcheck_result',
        ),
        migrations.RenameField(
            model_name='testsummary',
            old_name='cache_compatibility',
            new_name='code_gcov_result',
        ),
        migrations.RenameField(
            model_name='testsummary',
            old_name='cost_base',
            new_name='performance_base',
        ),
        migrations.RenameField(
            model_name='testsummary',
            old_name='cost_test',
            new_name='performance_test',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='exceptions',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='if_startmem',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='is_freeze',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='probe_result',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='pvscheck_block_num',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='pvscheck_result_link',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='regression_test_result',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='result_diff_precent',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='result_dmfgl',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='result_hcyzx',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='result_kpdiff',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='step',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='stress_test_cost',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='stress_test_cpu',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='stress_test_heap',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='stress_test_memory',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='stress_test_qps',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='test_cpu_performance',
        ),
        migrations.RemoveField(
            model_name='testsummary',
            name='testitem',
        ),
    ]
