# Generated by Django 2.1.1 on 2019-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSummary', '0002_auto_20190806_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsummary',
            name='testitem',
            field=models.IntegerField(default=0),
        ),
    ]
